name: OpenCart Tests
on: push
jobs:
  Add-to-cart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command : npm run test_prodpageE2E

      - name: Cypress report
        uses: actions/upload-artifact@v4
        with:
              name: Mochaawesome-report
              path: cypress/reports/html
  register-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command : npm run test_registertest

      - name: Cypress report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: Mochaawesome-report
            path: cypress/reports/html